'use client';
import DashboardMonth from '@/components/ui/Dashboard/DashboardMonth';
import DashBoardNav from '@/components/ui/Dashboard/DashboardNav';
import Header from '@/components/ui/Header/Header';
import Layout from '@/components/ui/Layout';
import { getList } from '@/http/crud';
import dayjs from 'dayjs';
import Head from 'next/head';
import { useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';

export default function Home() {
  const router = useRouter();

  const [date, setDate] = useState(dayjs().format('YYYY-MM-DD'));
  return (
    <>
      <Head>
        <title>Sviato-db | Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Header />
        <DashBoardNav setCurrentDate={setDate} year={2025} />
        <DashboardMonth
          day={dayjs(date).date()}
          month={dayjs(date).month() + 1}
        />
      </Layout>
    </>
  );
}
