import Button from '@/components/ui/Button';
import Calendar from '@/components/ui/Calendar';
import Input from '@/components/ui/Input';
import Layout from '@/components/ui/Layout';
import Textarea from '@/components/ui/Textarea';
import Typography from '@/components/ui/Typography';
import { createSviato } from '@/http/crud';
import Head from 'next/head';
import { useRouter } from 'next/navigation';
import { useState } from 'react';

export default function CreateSviato() {
  const router = useRouter();

  const [name, setName] = useState('');
  const [seoText, setSeoText] = useState('');
  const [date, setDate] = useState('');

  const [errors, setErrors] = useState<(string | undefined)[]>([
    undefined,
    undefined,
    undefined,
  ]);
  const validate = () => {
    const newErrors: (string | undefined)[] = [undefined, undefined, undefined];

    if (!name.trim()) {
      newErrors[0] = 'Name is required';
    }

    if (!seoText.trim()) {
      newErrors[1] = 'SEO text is required';
    }

    if (!date.trim()) {
      newErrors[2] = 'Date is required';
    }

    setErrors(newErrors);

    return newErrors.every((err) => err === undefined);
  };
  const handleSubmit = async () => {
    if (validate()) {
      const res = await createSviato({ name, seoText, timestamp: date });
      if (!res.ok) {
        alert('Виникла помилка під час створення');
        return;
      }
      router.replace('/');
    }
  };
  return (
    <>
      <Head>
        <title>Sviato-db | Add Sviato</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="flex flex-col gap-4 w-full ">
          <Typography type="title">Додати свято до БД</Typography>
          <div className="flex flex-col gap-2">
            <Input
              id="name"
              label="Назва*"
              value={name}
              onChange={(e) => setName(e.target.value)}
              error={errors[0]}
            />
            <Textarea
              id="seoText"
              label="SEO текст*"
              value={seoText}
              onChange={(e) => setSeoText(e.target.value)}
              error={errors[1]}
            />
            <Calendar
              id="date"
              label="Дата*"
              value={date}
              onChange={(d) => setDate(d)}
              error={errors[2]}
            />
            <Button onClick={handleSubmit}>Додати</Button>
          </div>
        </div>
      </Layout>
    </>
  );
}
