import Button from '@/components/ui/Button';
import Calendar from '@/components/ui/Calendar';
import Input from '@/components/ui/Input';
import Layout from '@/components/ui/Layout';
import SviatoDeleteModal from '@/components/ui/sviato/SviatoDeleteModal';
import Textarea from '@/components/ui/Textarea';
import Typography from '@/components/ui/Typography';
import { createSviato, deleteSviato, getOne, updateSviato } from '@/http/crud';
import Head from 'next/head';
import { useRouter, useSearchParams } from 'next/navigation';
import { useEffect, useState } from 'react';

export default function EditSviato() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const id = searchParams.get('id');
  const [name, setName] = useState('');
  const [seoText, setSeoText] = useState('');
  const [date, setDate] = useState('');
  const [open, setOpen] = useState(false);

  const [errors, setErrors] = useState<(string | undefined)[]>([
    undefined,
    undefined,
    undefined,
  ]);

  useEffect(() => {
    const fetch = async () => {
      if (!id) return;
      const res = await getOne(id);
      const json = await res.json();
      setName(json.sviato.name);
      setSeoText(json.sviato.seoText);
      setDate(json.sviato.timestamp);
    };
    fetch();
  }, [id]);

  const validate = () => {
    const newErrors: (string | undefined)[] = [undefined, undefined, undefined];

    if (!name.trim()) {
      newErrors[0] = 'Name is required';
    }

    if (!seoText.trim()) {
      newErrors[1] = 'SEO text is required';
    }

    if (!date.trim()) {
      newErrors[2] = 'Date is required';
    }

    setErrors(newErrors);

    return newErrors.every((err) => err === undefined);
  };
  const handleSubmit = async () => {
    if (validate() && id) {
      const res = await updateSviato({ id, name, seoText, timestamp: date });
      if (!res.ok) {
        alert('Виникла помилка під час створення');
        return;
      }
      router.replace('/');
    }
  };
  const deleteSviatoHandler = async () => {
    if (!id) return;
    const res = await deleteSviato(id);
    if (!res.ok) {
      alert('Виникла помилка під час видалення');
      return;
    }
    router.replace('/');
  };
  return (
    <>
      <Head>
        <title>Sviato-db | Edit Sviato</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="flex flex-col gap-4 w-full ">
          <div className="flex justify-between">
            <Typography type="title">Оновити свято</Typography>
            <Button type="danger" onClick={() => setOpen(true)}>
              Видалити
            </Button>
          </div>
          <div className="flex flex-col gap-2">
            <Input
              id="name"
              label="Назва*"
              value={name}
              onChange={(e) => setName(e.target.value)}
              error={errors[0]}
            />
            <Textarea
              id="seoText"
              label="SEO текст*"
              value={seoText}
              onChange={(e) => setSeoText(e.target.value)}
              error={errors[1]}
            />
            <Calendar
              id="date"
              label="Дата*"
              value={date}
              onChange={(d) => setDate(d)}
              error={errors[2]}
            />
            <Button onClick={handleSubmit}>Оновити</Button>
          </div>
        </div>
      </Layout>
      {open && (
        <SviatoDeleteModal
          isOpen={open}
          onClose={() => setOpen(false)}
          onDelete={deleteSviatoHandler}
        />
      )}
    </>
  );
}
